In [3]:
!pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 68.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 88.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 16.4 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.14.1
    Uninstalling scipy-1.14.1:
      Successfully uninstalled scipy-1.14.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.


In [1]:
!pip install --upgrade numpy
!pip install --upgrade gensim

  Using cached numpy-2.2.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Using cached numpy-2.2.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.2.5 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.5 which is incompatible.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 2.2.5 which is incompatible.
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
  A

In [4]:
import numpy as np
import gensim
print(gensim.__version__)

4.3.3


In [6]:
from gensim.models import Word2Vec , KeyedVectors

In [7]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [10]:
vec_king = wv['king']

In [17]:
vec_king.shape

(300,)

In [16]:
vec_king[:100]

array([ 0.12597656,  0.02978516,  0.00860596,  0.13964844, -0.02563477,
       -0.03613281,  0.11181641, -0.19824219,  0.05126953,  0.36328125,
       -0.2421875 , -0.30273438, -0.17773438, -0.02490234, -0.16796875,
       -0.16992188,  0.03466797,  0.00521851,  0.04638672,  0.12890625,
        0.13671875,  0.11279297,  0.05957031,  0.13671875,  0.10107422,
       -0.17675781, -0.25195312,  0.05981445,  0.34179688, -0.03112793,
        0.10449219,  0.06176758,  0.12451172,  0.40039062, -0.32226562,
        0.08398438,  0.0390625 ,  0.00585938,  0.0703125 ,  0.17285156,
        0.13867188, -0.23144531,  0.28320312,  0.14257812,  0.34179688,
       -0.02392578, -0.10986328,  0.03320312, -0.0546875 ,  0.01531982,
       -0.16210938,  0.15820312, -0.25976562,  0.0201416 , -0.16308594,
        0.00135803, -0.14453125, -0.05688477,  0.04296875, -0.0246582 ,
        0.18554688,  0.44726562,  0.00958252,  0.13183594,  0.09863281,
       -0.18554688, -0.10009766, -0.13378906, -0.125     ,  0.28

In [25]:
wv['madrid']

array([ 1.14257812e-01,  5.07812500e-02,  1.61132812e-01,  6.28906250e-01,
        6.34765625e-02, -2.16796875e-01, -4.51660156e-02, -1.25000000e-01,
       -1.40625000e-01,  1.46484375e-01, -6.00585938e-02, -3.71093750e-02,
       -2.00195312e-01,  1.63085938e-01,  2.50244141e-02,  2.79296875e-01,
        2.34375000e-01,  4.06250000e-01, -1.23046875e-01,  7.47070312e-02,
       -4.10156250e-02, -2.08007812e-01,  5.66406250e-01,  9.27734375e-02,
       -9.08203125e-02, -1.66992188e-01,  4.39453125e-02, -1.73828125e-01,
       -9.57031250e-02, -1.52343750e-01,  6.29882812e-02,  1.29882812e-01,
        9.13085938e-02, -2.17773438e-01, -1.56250000e-01,  3.49609375e-01,
       -2.85156250e-01,  9.81445312e-02,  1.03027344e-01,  4.33593750e-01,
        4.17480469e-02, -3.05175781e-02,  2.87109375e-01,  1.43554688e-01,
        3.37890625e-01, -2.89062500e-01,  4.84375000e-01, -3.02734375e-01,
       -3.37890625e-01,  1.70898438e-01, -1.66992188e-01,  2.67578125e-01,
        1.42578125e-01, -

In [27]:
wv.most_similar('food')

[('foods', 0.6804922819137573),
 ('Food', 0.6538903713226318),
 ('foodstuffs', 0.642582893371582),
 ('meals', 0.616668701171875),
 ('food_stuffs', 0.5928642153739929),
 ('nourishing_meals', 0.5847609043121338),
 ('foodstuff', 0.5835224986076355),
 ('staple_foods', 0.5535788536071777),
 ('nutritious', 0.5466451644897461),
 ('meal', 0.5433712601661682)]

In [29]:
wv.most_similar('happy')

[('glad', 0.7408890724182129),
 ('pleased', 0.6632170677185059),
 ('ecstatic', 0.6626912355422974),
 ('overjoyed', 0.6599286794662476),
 ('thrilled', 0.6514049172401428),
 ('satisfied', 0.6437949538230896),
 ('proud', 0.636042058467865),
 ('delighted', 0.627237856388092),
 ('disappointed', 0.6269949674606323),
 ('excited', 0.6247665286064148)]

In [30]:
wv.similarity('happy','glad')

0.74088913

In [32]:
vec = wv['king'] -wv['man'] + wv['woman']

In [35]:
vec[:100]

array([ 0.04296875, -0.17822266, -0.12908936,  0.11523438,  0.00268555,
       -0.10229492,  0.19580078, -0.1795044 ,  0.01953125,  0.40991974,
       -0.36816406, -0.39648438, -0.15673828,  0.00146484, -0.09301758,
       -0.11645508, -0.05517578, -0.10757446,  0.07910156,  0.19897461,
        0.23852539,  0.06340027, -0.02172852,  0.        ,  0.04724121,
       -0.21777344, -0.34472656,  0.0637207 ,  0.31640625, -0.19763184,
        0.0859375 , -0.08117676, -0.03710938,  0.31555176, -0.34179688,
       -0.046875  ,  0.09765625,  0.08398438, -0.09716797,  0.05175781,
       -0.05004883, -0.22094727,  0.22949219,  0.12640381,  0.24902344,
        0.02099609, -0.10986328,  0.05810547, -0.03356934,  0.12957764,
        0.02416992,  0.03481293, -0.26000977,  0.24230957, -0.32177734,
        0.01454163, -0.15917969, -0.08374023,  0.16503906,  0.00158691,
        0.3095703 ,  0.31640625,  0.00738525,  0.24121094,  0.04907227,
       -0.09863281,  0.02905273,  0.14941406, -0.04833984,  0.23

In [33]:
wv.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]