# Naive Bayes Machine Learning Algorithms Implemetation

## Import Library and dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_iris

In [4]:
X,y=load_iris(return_X_y=True)

In [5]:
X.shape , y.shape

((150, 4), (150,))

## Split Data into train and test

In [3]:
from sklearn.model_selection import  train_test_split

In [6]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

## Gaussian Naiv's Bayes

In [7]:
from sklearn.naive_bayes import GaussianNB

In [8]:
gnb = GaussianNB()

In [9]:
gnb.fit(X_train,y_train)

GaussianNB()

In [10]:
Y_preds = gnb.predict(X_test)

In [17]:
# Evaluation Metrics
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print("accuracy score : " , accuracy_score(y_test,Y_preds))
print("----------------------------------------------")
print("confusion matrix : " )
print(confusion_matrix(y_test,Y_preds))
print("---------------------------------")
print("classification report : " )
print(classification_report(y_test,Y_preds))

accuracy score :  1.0
----------------------------------------------
confusion matrix : 
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
---------------------------------
classification report : 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



## New Dataset

In [21]:
df = sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [25]:
df.drop(columns=['day'] , inplace=True)

In [26]:
df.head()

total_bill   tip     sex smoker    time  size
0       16.99  1.01  Female     No  Dinner     2
1       10.34  1.66    Male     No  Dinner     3
2       21.01  3.50    Male     No  Dinner     3
3       23.68  3.31    Male     No  Dinner     2
4       24.59  3.61  Female     No  Dinner     4

### Features Encoding

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   time        244 non-null    category
 5   size        244 non-null    int64   
dtypes: category(3), float64(2), int64(1)
memory usage: 6.9 KB


In [22]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [28]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [29]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [30]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder

In [31]:
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [32]:
# we convert the three columns into binary values
df['sex'] = le1.fit_transform(df['sex'])
df['time'] = le2.fit_transform(df['time'])
df['smoker'] = le3.fit_transform(df['smoker'])

In [33]:
df

total_bill   tip  sex  smoker  time  size
0         16.99  1.01    0       0     0     2
1         10.34  1.66    1       0     0     3
2         21.01  3.50    1       0     0     3
3         23.68  3.31    1       0     0     2
4         24.59  3.61    0       0     0     4
..          ...   ...  ...     ...   ...   ...
239       29.03  5.92    1       0     0     3
240       27.18  2.00    0       1     0     2
241       22.67  2.00    1       1     0     2
242       17.82  1.75    1       0     0     2
243       18.78  3.00    0       0     0     2

[244 rows x 6 columns]

### Split Data into Training and test data

In [34]:
X= df.drop(columns=['smoker'])
y=df['smoker']

In [35]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [36]:
gnb = GaussianNB()

In [37]:
gnb.fit(X_train,y_train)

GaussianNB()

In [38]:
y_pred2 = gnb.predict(X_test)

In [39]:
# Evaluation Metrics
print("accuracy score : " , accuracy_score(y_test,y_pred2))
print("----------------------------------------------")
print("confusion matrix : " )
print(confusion_matrix(y_test,y_pred2))
print("---------------------------------")
print("classification report : " )
print(classification_report(y_test,y_pred2))

accuracy score :  0.6326530612244898
----------------------------------------------
confusion matrix : 
[[30  1]
 [17  1]]
---------------------------------
classification report : 
              precision    recall  f1-score   support

           0       0.64      0.97      0.77        31
           1       0.50      0.06      0.10        18

    accuracy                           0.63        49
   macro avg       0.57      0.51      0.43        49
weighted avg       0.59      0.63      0.52        49

